### ISSUE TITLE
运行gulp server的时候出错

### ISSUE THREAD

**Issue by LiangZugeng** [tinglejs/tingle-scroller#4]
我把项目clone到本地，然后npm install，再运行npm run start或者gulp server后，出现eslint报错，附上报错信息。

这里有一个疑问：既然源码里面包含了iscroll.js，理论上来说应该能够通过eslint的检查，否则不是开发环境都没有办法搭建？望指教。

gulp@3.9.1
eslint@2.13.1
npm@3.10.10
node.js@6.9.4

`C:\Users\lzg\Documents\Projects\Learning\tingle-scroller>gulp server
[21:23:58] Using gulpfile ~\Documents\Projects\Learning\tingle-scroller\gulpfile.js
[21:23:58] Starting 'pack_demo'...
The react/jsx-sort-prop-types rule is deprecated. Please use the react/sort-prop-types rule instead.
The eslint went wrong

C:\Users\lzg\Documents\Projects\Learning\tingle-scroller\src\iscroll.js

║ Line     │ Column   │ Type     │ Message                                                │ Rule ID              ║
╟──────────┼──────────┼──────────┼────────────────────────────────────────────────────────┼──────────────────────╢
║ 64       │ 27       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 68       │ 46       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 94       │ 69       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 133      │ 10       │ error    │ Expected a conditional expression and instead saw      │ no-cond-assign       ║
║          │          │          │ an assignment.                                         │                      ║
║ 183      │ 27       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 196      │ 23       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 198      │ 21       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 199      │ 29       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 200      │ 21       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 201      │ 29       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 203      │ 29       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 214      │ 12       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 216      │ 12       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 249      │ 27       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 298      │ 55       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 299      │ 55       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 305      │ 63       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 313      │ 37       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 319      │ 30       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 379      │ 17       │ error    │ Expected '!==' and instead saw '!='.                   │ eqeqeq               ║
║ 392      │ 32       │ error    │ Expected '!==' and instead saw '!='.                   │ eqeqeq               ║
║ 398      │ 25       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 481      │ 29       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 482      │ 39       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 484      │ 46       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 490      │ 36       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 491      │ 39       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 493      │ 46       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 533      │ 32       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 624      │ 13       │ error    │ Expected '!==' and instead saw '!='.                   │ eqeqeq               ║
║ 624      │ 31       │ error    │ Expected '!==' and instead saw '!='.                   │ eqeqeq               ║
║ 665      │ 10       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 665      │ 25       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 773      │ 17       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 932      │ 49       │ error    │ Expected '!==' and instead saw '!='.                   │ eqeqeq               ║
║ 1126     │ 15       │ error    │ Expected '!==' and instead saw '!='.                   │ eqeqeq               ║
║ 1126     │ 33       │ error    │ Expected '!==' and instead saw '!='.                   │ eqeqeq               ║
║ 1142     │ 14       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 1315     │ 33       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 1465     │ 10       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 1477     │ 10       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 1574     │ 40       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 1576     │ 45       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 1715     │ 32       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 1772     │ 35       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 1796     │ 17       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 1822     │ 35       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 1971     │ 40       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 2008     │ 25       │ error    │ Expected '!==' and instead saw '!='.                   │ eqeqeq               ║
║ 2008     │ 54       │ error    │ Expected '!==' and instead saw '!='.                   │ eqeqeq               ║
║ 2082     │ 29       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 2090     │ 50       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 2090     │ 79       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 2104     │ 29       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 2113     │ 50       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 2113     │ 79       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 2125     │ 30       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 2131     │ 30       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 2138     │ 36       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 2138     │ 61       │ error    │ Expected '!==' and instead saw '!='.                   │ eqeqeq               ║
║ 2144     │ 30       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 2150     │ 30       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 2157     │ 36       │ error    │ Expected '===' and instead saw '=='.                   │ eqeqeq               ║
║ 2157     │ 62       │ error    │ Expected '!==' and instead saw '!='.                   │ eqeqeq               ║
║ 2208     │ 33       │ warning  │ Gratuitous parentheses around expression.              │ no-extra-parens      ║
║ 2217     │ 20       │ error    │ Expected '!==' and instead saw '!='.                   │ eqeqeq               ║

C:\Users\lzg\Documents\Projects\Learning\tingle-scroller\src\Scroller.js

║ Line     │ Column   │ Type     │ Message                                                │ Rule ID              ║
╟──────────┼──────────┼──────────┼────────────────────────────────────────────────────────┼──────────────────────╢
║ 29       │ 5        │ warning  │ componentDidUnMount should be placed before render     │ react/sort-comp      ║
║ 59       │ 27       │ warning  │ The closing bracket must be aligned with the           │ react/jsx-closing-   ║
║          │          │          │ opening tag (expected column 13 on the next line)      │ bracket-location     ║

╔════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ 48 Errors                                                                                                      ║
╟────────────────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ 20 Warnings                                                                                                    ║
╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝

[21:24:00] 'pack_demo' errored after 1.79 s
[21:24:00] Error: eslint error
    at formatError (C:\Users\lzg\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^3.7.0\formatError.js:20:10)
    at Gulp.<anonymous> (C:\Users\lzg\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^3.7.0\log\events.js:41:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (C:\Users\lzg\Documents\Projects\Learning\tingle-scroller\node_modules\orchestrator\index.js:264:8)
    at C:\Users\lzg\Documents\Projects\Learning\tingle-scroller\node_modules\orchestrator\index.js:275:23
    at finish (C:\Users\lzg\Documents\Projects\Learning\tingle-scroller\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (C:\Users\lzg\Documents\Projects\Learning\tingle-scroller\node_modules\orchestrator\lib\runTask.js:29:3)
    at Gulp.<anonymous> (C:\Users\lzg\Documents\Projects\Learning\tingle-scroller\node_modules\tingle-dev-tools\gulpfile.js:76:5)
    at module.exports (C:\Users\lzg\Documents\Projects\Learning\tingle-scroller\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\lzg\Documents\Projects\Learning\tingle-scroller\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\lzg\Documents\Projects\Learning\tingle-scroller\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\lzg\Documents\Projects\Learning\tingle-scroller\node_modules\orchestrator\index.js:134:8)
    at C:\Users\lzg\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:46:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by gbk** [comment]
很抱歉，tingle-* 组件已经迁移到 saltui 项目，saltui 项目仍在孵化中尚未开源，你可以参考[这里](https://github.com/saltjs/salt-ui)使用。

**Comment by LiangZugeng** [comment]
因为Tingle组件的文档和Demo在官网上不全，saltui的参考更少，所以昨天找到TingleJS源码还很是高兴了一阵子，听闻Salt-UI尚未开源，感觉又要回到黑暗中摸索了。

目前的问题确实是Tingle和Salt-UI的参考资料少，文档也存在一些问题，比如tingle-scroll-list找不到任何源码和Demo，Scroller也找不到任何Live demo，还有在tingle官方文档中的某些链接指向到阿里内部gitlab服务器，外面访问不了，例如tingle-icon这一节里面的“使用公共 icon“。

我们一个月前开始做阿里钉钉的开发，按照官网的指导使用了Natty-Fetch和Salt-UI，其实后端都很简单，早就打通了，前端由于团队以前是做C#和ASP.NET的所以花了很多时间摸索前端的技术，Natty-Fetch基本没有问题，就是界面控件的参考太少，Salt-UI的Demo不全（比如Scroller没有），加上没有开源，自己探索的难度很大。之前尝试过在钉钉官网的开发者支持上提出过问题，但感觉开发者支持板块都是前端客服在负责，对于技术问题很难得到有效的帮助。我对Natty-Fetch和Salt-UI的帮助全部都是在GitHub上获得的。

Salt-UI开源时间有计划吗？或者参考资料的整理有没有考虑把tingle的文档和salt-ui文档整合并提高质量？或者提供更好的社区支持？比如把社区支持移到github或者stackoverflow或者类似地方？

**Comment by eternalsky** [comment]
@LiangZugeng 我们近期会上线，新的 SaltUI 组件官网，附加 LiveDemo 等功能。

**Comment by LiangZugeng** [comment]
嗯，期待，感谢阿里团队对开源的贡献，希望以后越做越好
