### ISSUE TITLE
Scroller在Chrome的Mobile View下不工作

### ISSUE THREAD

**Issue by LiangZugeng** [tinglejs/tingle-scroller#5]
环境：Win10 x64最新补丁，Chrome@56.0.2924.87。
repro示例的地址：https://github.com/LiangZugeng/scroller-bug-repro.git

重现步骤：
1. 确保安装了最新版的nowa
2. Clone项目
3. 进入项目，执行npm run start
4. 打开Chrome，访问http://localhost:3000
5. 打开Chrome的developer tool，点击移动设备按钮切换到移动设备视图，选择任意一个iPhone的屏幕配置，尝试使用鼠标拖动列表，不工作。见附图。
![image](https://cloud.githubusercontent.com/assets/20870130/22932550/49672afa-f303-11e6-8348-b4734dd445ed.png)

另外提一点：在正常Chrome视图下Scroller是工作的，能正确响应鼠标拖动事件并且能正确触发onScrollEnd事件。

**Comment by alex-mm** [comment]
一般刷新下就好了

**Comment by gbk** [comment]
Chrome 55 引入了一些新特性，导致 iscroll 无法支持
https://github.com/cubiq/iscroll/issues/1109

请参考 [PR](https://github.com/LiangZugeng/scroller-bug-repro/pull/1/files) 修改。

**注意**，这些修改只是为了让 scroller 在 Chrome 55+ 中跑起来，对手机各机型未做完整测试，手机上不建议做上述修改。

**Comment by LiangZugeng** [comment]
谢谢帮忙，没有live demo还真不知道要在componentDidMount里面刷新Scroller。

我测试了@gbk建议的修改，在Chrome下各种View都工作正常了，iPhone的iOS 10.2下也没问题，Android平台4.2/4.4/5.0/5.1内置浏览器也都没问题，但Android 6.0 MarshMellow的内置浏览器拖不动，是不是iscroll的兼容性不好？这应该跟Scroller封装没关系吧？

我们程序运行在阿里钉钉的Web View中，@gbk你知不知道国内哪家手机开始使用Android 6.0的内核定制系统了？阿里钉钉在6.0安卓下运行正常吗？

**Comment by gbk** [comment]
不清楚。。你搜一下吧

不能使用可能跟 iscroll 兼容性有关

**Comment by LiangZugeng** [comment]
Thanks, issue closed.
